"""
Pydantic models for OpenAI-compatible Embeddings endpoints.

This module defines the data structures for creating text embeddings,
ensuring compatibility with the OpenAI API specification.
"""

from typing import List, Union, Optional, Literal, Annotated
from ovos_persona_server.config import settings
from pydantic import BaseModel, Field


class Embedding(BaseModel):
    """
    Represents an embedding vector returned by the embedding endpoint.
    """
    object: Literal["embedding"] = Field("embedding", description="The object type, which is always `embedding`.")
    embedding: List[float] = Field(..., description="The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the [embedding guide](/docs/guides/embeddings).")
    index: int = Field(..., description="The index of the embedding in the list of embeddings.")


class Usage(BaseModel):
    """
    Usage statistics for the embedding request.
    """
    prompt_tokens: int = Field(..., description="The number of tokens in the prompt.")
    total_tokens: int = Field(..., description="The total number of tokens used in the request.")


class CreateEmbeddingRequest(BaseModel):
    """
    Request body for creating embeddings.
    """
    input: Union[
        str,
        Annotated[List[str], Field(min_length=1, max_length=2048)],
        Annotated[List[int], Field(min_length=1, max_length=2048)],
        Annotated[List[List[int]], Field(min_length=1, max_length=2048)]
    ] = Field(
        ...,
        description=(
            "Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, "
            "pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the "
            "model (8192 tokens for all embedding models), cannot be an empty string, and any array must be 2048 "
            "dimensions or less. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) "
            "for counting tokens. In addition to the per-input token limit, all embedding models enforce a maximum of "
            "300,000 tokens summed across all inputs in a single request."
        )
    )
    model: Optional[str] = Field(settings.embeddings_model, description="ID of the model to use.")
    encoding_format: Optional[Literal["float", "base64"]] = Field("float", description="The format to return the embeddings in.")
    dimensions: Optional[int] = Field(None, description="The number of dimensions the resulting output embeddings should have.")
    user: Optional[str] = Field(None, description="A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.")


class CreateEmbeddingResponse(BaseModel):
    """
    Response body for an embeddings request, containing a list of embedding objects.
    """
    object: Literal["list"] = Field("list", description="The object type, which is always `list`.")
    data: List[Embedding] = Field(..., description="The list of embeddings generated by the model.")
    model: Optional[str] = Field(settings.embeddings_model, description="The name of the model used to generate the embedding.")
    usage: Usage = Field(..., description="The usage information for the request.")
