name: Build Tests
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    secrets: inherit
    with:
      install_extras: "dev,mcp"
      test_path: "tests"
